### ISSUE TITLE
Coffee & Tea should be nerfed

### ISSUE THREAD

**Issue by gdunstone** [juanosarg/VanillaBrewingExpanded#1]
Selling coffee or tea shouldn't be more profitable than selling flake. Comparing profit per day (ppd), alongside grow time gives a good metric for the strength of a particular crop.

I suggest the following changes, I can open a pull request for it if you like:

1. reduce the MarketValue of VBE_RawCoffee to 0.9, this brings the ppd down from 3.9 to 1.875 (compared to 1.68 for psychoid leaves profit) and means that producing coffee from beans increases the value rather than reducing it, with full process ppd (excluding work) being ~3.33 (compared to flakes being ~3.11).
2. reduce the MarketValue of VBE_RawTea to 0.85, this brings the ppd down from 3.8 to 1.7. This also means that turning tea leaves into tea increases value, with full process ppd (excluding work) being ~3.2.

These changes bring Coffee and Tea more into line with profitability when compared to Flake.

**Comment by gdunstone** [comment]
I also had a look at Tobacco:

The current tobacco ppd for just the leaves is ~2.23 with ppd for full process (cigarettes) being ~1.88

I propose the following changes to tobacco:

1. reduce the MarketValue of VBE_RawTobacco to 1.5, this brings the ppd down to 1.76
2. increase the MarketValue of VBE_Cigarette to 12, this brings the ppd up to 2.82

**Comment by gdunstone** [comment]
I created a pull request for these changes here https://github.com/juanosarg/VanillaBrewingExpanded/pull/2

**Comment by juanosarg** [comment]
So, I've asked OSkar and Balistafreak for review, because I'd rather kill myself than think about this nuance. You and I are playing a WILDLY different game lol

**Comment by gdunstone** [comment]
Lol, no worries mate.

I only noticed because someone in a steam comment mentioned it and I agreed that it was a bit weird that it was more profitable to be a barista than a crack dealer.
